kafka_settings:
  billing: blusalt_billing
spring:
  application:
    name: 'consumer_service'
  sql:
    init:
      mode: 'always'
  kafka:
    bootstrap-servers: 'localhost:9092'
  datasource:
    url: 'jdbc:h2:mem:blusalt_test_db_mc'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false
